system:
  addr: ":8080"
  database:
    mysqlhost: "localhost"
    mysqlport: "3306"
    mysqluser: "root"
    mysqlpassword: "root"
    mysqldatabasename: "kube"
  elasticsearch:
    eshost: "eshost.natapp1.cc"
    esport: "80"
    username: "elastic"
    password: "123456"
