system:
  addr: ":8080"
  database:
    mysqlhost: "localhost"
    mysqlport: "3306"
    mysqluser: "root"
    mysqlpassword: "166490"
#    mysqldatabasename: "kube"
  elasticsearch:
    eshost: "192.168.163.66"
    esport: "9200"
    username: "elastic"
    password: "123456"
  alertmanger_api:
    host: "192.168.163.66"
    port: "9093"